spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/motor?characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    password: nhnacademy
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true


eureka:
  client:
    enabled: false



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: info