spring:
  datasource:
    username: sa
    url: jdbc:h2:./db:testdb;AUTO_SERVER=TRUE;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true

eureka:
  client:
    enabled: false




