spring:
  datasource:
    username: ${MYSQL_USERNAME}
    url: ${MYSQL_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.23:8761/eureka
    enabled: true

influx:
  url: ${INFLUX_URL}
  username: ${INFLUX_USERNAME}
  password: ${INFLUX_PASSWORD}
  org: aiotone
  bucket: ai
