spring:
  application:
    name: monitoring-service
  datasource:
    username: ${MYSQL_USERNAME}
    url: ${MYSQL_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}