spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    enabled: false

