
### 섹터 목록 조회
GET http://localhost:8080/api/monitor/sectors

### 섹터 등록
POST http://localhost:8080/api/monitor/sectors
Content-Type: application/json

{
  "sectorName": "sector1"
}

### 공장 전체 모터 상태 요약 정보 조회
GET http://localhost:8080/api/monitor/overview


### 섹터 요약 정보 조회
GET http://localhost:8080/api/monitor/sectors/overview


### 총 모터 가동률 조회
GET http://localhost:8080/api/monitor/motors/running-rate

### 개별 모터 가동률 정보 조회
GET http://localhost:8080/api/monitor/motors/3/running-rate?duration=MONTH
